### ISSUE TITLE
编译后的文件没有上传对应的dll

### ISSUE THREAD

**Issue by wanglz111** [wu-yafeng/QQSG_DecodePkg#2]
编译后的文件里没有上传dll/deps/pdb等文件导致无法运行

可以考虑重新上传编译后的文件

**Comment by wu-yafeng** [comment]
我重新编译了self-contained版本。现在不需要安装任何运行时了，但是此版本可能导致git clone失败

可以[在此](https://github.com/wu-yafeng/QQSG_DecodePkg/releases/tag/1.0.0 )下载exe文件
