### ISSUE TITLE
这个游戏的lua貌似都是UI相关的逻辑

### ISSUE THREAD

**Issue by alienwu2018** [wu-yafeng/QQSG_DecodePkg#3]
这个游戏完完全全的纯服务端游戏，数据基本上全是服务端下发，服务端计算。客户端的lua层是拿来写UI逻辑，感觉没什么实际可用之处。我想到的是理论上是可以hook lua来获取自动获取各种数据，比方说摆摊，商行等等，其他用处真没想到了，改点UI的逻辑对游戏性本身不痛不痒

**Comment by wu-yafeng** [comment]
lua的主要作用是开发脚本
游戏里的一些功能：
1. 在霸王城受到攻击时自动使用置身道具
2. 自动寻路
3. 自动切仓
4. 自动浏览摊位记录到数据库

c++主要是做一些渲染和控制的逻辑，同时还做了一部分的lua->请求转发。lua则是交互类的逻辑。
