### ISSUE TITLE
想问一下大佬是如何逆向出来的

### ISSUE THREAD

**Issue by fake2ky** [wu-yafeng/QQSG_DecodePkg#4]
最近又重拾了QQSG这游戏，解包的时候发现加密。。 然后看到了大佬的仓库，这个应该是tea的加密吗? 
如果能说说过程，小弟不胜感激

**Comment by wu-yafeng** [comment]
我是基于客户端的汇编代码分析出加密的算法和密钥的。
看加密的算法更像是AES加密（随机-迭代异或），但是我用C#的AES库的是解密不出来的。这游戏的代码和库都太老了，可能目前编程语言所使用的库都已经无法兼容之前的AES算法了。

**Comment by fake2ky** [comment]
![image](https://github.com/wu-yafeng/QQSG_DecodePkg/assets/31437813/3977dc46-c831-408c-8ab6-db1d8b678f2b)
我在IDA尝试只找到了解密的部分(key部分是要动态调试?), 但是这也是上帝视角找出来的, 因为本身就知道了解密部分~~,  对调试这方面不太了解大佬能指点一下么 这是我的QQ413400524

**Comment by wu-yafeng** [comment]
> ![image](https://user-images.githubusercontent.com/31437813/250357195-3977dc46-c831-408c-8ab6-db1d8b678f2b.png) 我在IDA尝试只找到了解密的部分(key部分是要动态调试?), 但是这也是上帝视角找出来的, 因为本身就知道了解密部分~~, 对调试这方面不太了解大佬能指点一下么 这是我的QQ413400524

这部分对应了此仓库的decrypt_block 函数部分，IDA可以查找交叉引用（点击函数让光标停留在函数处，按键盘X键），只要一直找引用，总有地方传密钥的

你的QQ应该是设置了什么，我这里无法搜到

**Comment by fake2ky** [comment]
> 
> 这部分对应了此仓库的decrypt_block 函数部分，IDA可以查找交叉引用（点击函数让光标停留在函数处，按键盘X键），只要一直找引用，总有地方传密钥的
> 
> 你的QQ应该是设置了什么，我这里无法搜到

确实关闭了搜索 ,  现在应该能搜到了
