### ISSUE TITLE
十分感谢

### ISSUE THREAD

**Issue by nkxb1008** [wu-yafeng/QQSG_DecodePkg#6]
十分感谢，是否能实现修改好以后加密回去呢？

**Comment by wu-yafeng** [comment]
不知道，游戏应该有完整性校验。打包回去挺麻烦的，不如直接注入改内存方便

**Comment by nkxb1008** [comment]
比如果说制作一个黑屏客户端，游戏有MD5校验

**Comment by nkxb1008** [comment]
一个pkg文件，不能全部解压出来，还有些文件没有解压出来

**Comment by wu-yafeng** [comment]
> 一个pkg文件，不能全部解压出来，还有些文件没有解压出来

只解压了txt和lua格式的，其他格式的文件需要解压的话可以修改 Program.cs 中的 export_types 字段后重新编译运行就行了

**Comment by nkxb1008** [comment]
如果我不去选择，我也不知道有多少个文件类型，我想直接全部解压，不要单独去填写后缀名，需要解密要保留，其他全部解压
